spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartcafe
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "oioioi"

